Create joinLobby endpoint
Orlando-Silva/cat-game-backend pull request #12
Opened 2024-05-01 00:18 UTC by samuel-marafigo

2024-05-01 06:04 UTC, Orlando-Silva reviewed
Deixei bastante comentário mas você fez tudo muito bem. You 🪨 . É uma tarefa difícil e você conseguiu executar muito bem

2024-05-01 06:04 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/api/LobbyAPI.kt
> +        lobbyService.joinLobby(roomId, joinLobbyDTO.userName)
Podemos passar o `JoinLobbyDTO` inteiro para o método

2024-05-01 06:04 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/api/dto/JoinLobbyDTO.kt
> +    val userName: String
Adicionar anotation para verificar se o username foi preenchido 
```suggestion
   @Size(min = 1, max = 50, message = "Username must be filled")
    val userName: String
```

2024-05-01 06:04 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/domain/services/LobbyService.kt
> +        println(lobbyId)
Podemos remover essa linha. Sei que ela foi usada para fins de testes para verificar se ele estava conseguindo encontrar na base de dados, mas essa linha, no código final, não terá utilidade

2024-05-01 06:04 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/domain/services/LobbyService.kt
> +        val lobby = lobbyRepository.findById(lobbyId).orElseThrow { CatGameLobbyNotFoundException("Lobby does not exist.") }
Podemos buscar o lobby inteiro de uma vez. Não precisamos bater no banco duas vezes
```suggestion
        val lobby = lobbyRepository.findByRoomId(roomId).orElseThrow { CatGameLobbyNotFoundException("Lobby does not exist.") }
```

2024-05-01 06:04 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/domain/services/LobbyService.kt
> +        if (lobby.status != Status.PENDING) {
Ótimo uso de guard clause

2024-05-01 06:04 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/domain/services/PlayerService.kt
> +    fun countPlayersInLobby(lobbyId: Long): Int {
Essa função não está sendo usada, podemos remover ela

2024-05-01 06:04 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/infra/repositories/LobbyRepository.kt
> +    fun findIdByRoomId(roomId: UUID): Long?
Essa segunda query não precisa existir

2024-05-01 06:04 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/infra/repositories/PlayerRepository.kt
> +    fun countByLobbyId(lobbyId: Long): Int
Essa query não precisa existir

2024-05-01 06:04 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/infra/repositories/PlayerRepository.kt
> +    fun findAllPlayersByLobbyId(lobbyId: Long): List<Player>
Acho que não é necessário usar a anotação query aqui. Acho que apenas findByLobbyId

2024-05-01 06:04 UTC, Orlando-Silva commented on src/test/kotlin/com/game/catbackend/data/PlayerBuilder.kt
> +    private var lobbyId: Long = 0
Aqui pode ser uma instância da classe Player ao invés de campo a campo. Veja a implementação do Builder do Image

2024-05-01 06:04 UTC, Orlando-Silva commented on src/test/kotlin/com/game/catbackend/domain/services/LobbyServiceTests.kt
> +    fun `when joinLobby is called with valid conditions it should add a player`() {
Bons testes!!

2024-05-28 02:19 UTC, Orlando-Silva requested changes

2024-05-28 02:19 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/api/LobbyAPI.kt
> +        val response = mapOf(
Criar uma classe para isso

2024-05-28 02:19 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/api/dto/JoinLobbyDTO.kt
> +class JoinLobbyDTO(
data

2024-05-28 02:19 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/domain/services/LobbyService.kt
> +        return playerList.map { it.username }
mover para o joinLobby

2024-05-28 02:19 UTC, Orlando-Silva commented on src/main/kotlin/com/game/catbackend/infra/repositories/PlayerRepository.kt
> +    fun findAllPlayersByLobbyId(lobbyId: Long): List<Player>
```suggestion
    fun findAllByLobbyId(lobbyId: Long): List<Player>

```

2024-05-28 02:19 UTC, Orlando-Silva commented on src/test/kotlin/com/game/catbackend/data/PlayerBuilder.kt
> +        println(player.id)
Remover esse print

2024-05-28 03:50 UTC, Orlando-Silva submitted a review, later dismissed

2024-05-28 03:54 UTC, sakataalan approved these changes
🦩

2024-05-28 03:55 UTC, merged